spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    name: omerkincal
    json:
      name: omerkincal_json
  exchange:
    name: omerkincal_exchange
  routing:
    key: omerkincal_routing_key
    json:
      key: omerkincal_json_routing_key